### ISSUE TITLE
suggestion: deliver Monolog without composer

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/cockpit-logger-addon#3]
A few hours ago I tried Logger with `composer create-project pauloamgomes/logger Logger`. After fixing some issues I realized, that I installed an old version by accident. I downloaded the repo, called `composer install` and it worked much better.

I'm not 100% sure about this warning:

`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.`

And you should add `composer.lock` to `.gitignore`.

**Comment by pauloamgomes** [comment]
Thanks, Raffael, and apologies for late answer, but a bit busy in the work.. 
Yes, having composer.lock in the .gitignore make sense, but still prefer the have Monolog installed via composer.

**Comment by raffaelj** [comment]
> and apologies for late answer

No problem.
