### ISSUE TITLE
How to add custom events?

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/cockpit-logger-addon#4]
I think about a way to implement logging in addons, but I didn't find a way to add custom triggers to your addon. Some problems:

1. I have to check if the logger addon exists.
2. If it is installed, I want to add a new on/off switch in the logger settings
3. If Logger exists and my event is enabled, the event should call logger

I found a way to adjust it via `config.yaml`.

config.yaml:
```yaml
logger:
    events:
        - name: my.custom.trigger
          enabled: false
```

bootstrap.php:
```
if (isset($this['modules']['logger'])) {

    $this->set('config/logger/events', array_replace_recursive(
        [['name' => 'my.custom.trigger', 'enabled' => true]],
        $this->retrieve('logger/events', [])
    ));

    $this->on('my.custom.trigger', function() {
        if (!$this->module('logger')->eventEnabled('my.custom.trigger')) {
            return;
        }
        $this->module('logger')->notice('My custom trigger');
    });

}

$this->on('cockpit.account.login.error', function ($user) {
    $this->module('logger')->notice($user.' failed on login');
    $this->trigger('my.custom.trigger');
});
```

It works, but it is really complicated if I want to add more events. This way, I have a pretty on/off switch in the settings for my.custom.trigger with no effect, too.

What do you think?

**Comment by pauloamgomes** [comment]
Yep, but think found a better solution, added a custom trigger, so you can use in your addon something like:

```
// Custom levels
$app->trigger('logger.event', ['notice', 'this is a custom log event']);
$app->trigger('logger.event', ['error', 'this is a custom log event']);
// With extra options
$extraArgs = ['action' => 'save'];
$app->trigger('logger.event', ['error', 'this is a custom log event', $extraArgs]);
```

Please confirm that works well on your end.

**Comment by raffaelj** [comment]
I'm really tired now and I have much work to do in the next days. I can't promise to find some time for it tomorrow, but maybe in the next days.

**Comment by raffaelj** [comment]
It works.

```php
try {
    // PDO connection
}
catch(\PDOException $e) { // connection failed

    // nothing happens:
    $app->trigger('logger.event', ['notice', $e->getMessage()]);

    // this works and my message is logged on each request:
    $app->on('admin.init', function() use ($e) {
        $this->trigger('logger.event', ['notice', 'db connection error']);
    });

    // That's, what I do instead:
    define('COCKPIT_TABLES_CONNECTED', false);
    // Now I can do my own error handling.

}
```

The trick with passing the error to the admin.init event seems to be the best method. 

Besides this, I'm not really happy with the alphabetical addon loading order and the fact, that I throw errors on each request.

**Comment by pauloamgomes** [comment]
Thats good, in such case the addon can be improved further..when have some spare time..

Yep, I have the same concern, the weight for me make all sense, or just having the list of addons on the config.yaml

```
addons:
 - addonA
 - addonB
 - addonC
```  

so cockpit would load on the exact order defined above

**Comment by raffaelj** [comment]
Well... I should sleep right now instead of hacking unintended cockpit options, but I had this idea in my head... With this workaround, you can load all addons in your preferred order:

Content of `config/config.php`:

```php
<?php

// store your config here or load the yaml file
$config = Spyc::YAMLLoad(COCKPIT_CONFIG_DIR.'/config.yaml');

$config['modules.disabled'] = [];

$dirs = array_merge([
    COCKPIT_DIR.'/modules',  # core
    COCKPIT_DIR.'/addons' # addons
], $config['loadmodules'] ?? []);

foreach ($dirs as $dir) {

    // don't name "$m" "$module"! This variable is already taken.
    foreach (new \DirectoryIterator($dir) as $m) {

        if ($m->isFile() || $m->isDot()) continue;
        if ($m->getBasename() == 'Cockpit') continue;

        $config['modules.disabled'][] = $m->getBasename();
        $config['modules.paths'][$m->getBasename()] = $m->getRealPath();

    }

}

$config['modules.order'] = [
    'Logger',
    'Collections',
    'Singletons',
    // '...',
];

return $config;
```

Content of `config/bootstrap.php`:

```php
<?php

foreach($app['modules.order'] as $m) {

    $app->registerModule($m, $app['modules.paths'][$m]);

}
```

**Comment by raffaelj** [comment]
And now I wrote an addon to specify the boot order of all modules:
https://github.com/raffaelj/cockpit_BootManager/

**Comment by pauloamgomes** [comment]
That seems really interesting.. nice job 👍
