### ISSUE TITLE
unable to log during bootstrap

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/cockpit-logger-addon#5]
Today I tried to log errors during bootstrap and it wasn't possible, because Logger builds itself on `cockpit.bootstrap`, which is triggered later than `loadModules()` is called.

It worked after simply removing the surrounding `$app->on('cockpit.bootstrap)`:
https://github.com/pauloamgomes/cockpit-logger-addon/blob/master/bootstrap.php#L277
https://github.com/pauloamgomes/cockpit-logger-addon/blob/master/bootstrap.php#L333

My simplified use case:

```php
try {
    // PDO connection
}
catch(\PDOException $e) { // connection failed
    $this->module('logger')->error($e->getMessage());
}
```

... Well, now I tried some more and my solution above only works if my test addon is loaded alphabetically after "Logger". So the best solution would be a global logging system from cockpit itself... And renaming your addon to "00Logger" sounds bad and hacky (but funny).

And finally I found an easy way to use your addon from different places. Maybe you're interested: https://github.com/pauloamgomes/cockpit-logger-addon/commit/c7ee318de8f3158a442198f676800ca25327c652

With the commit above It's easy to log during bootstrap, but there is still the problem with alphabetical order of loaded modules.

```php
if (isset($this['modules']['logger'])) {
  $this->module('logger')->init();
  $this->module('logger')->error($e->getMessage());
}
And I can use custom settings with `$this->module('logger')->init($custom_settings);`
```

**Comment by pauloamgomes** [comment]
Yeah, the alphabetical loading order is still an issue... I remember to mention before to have a weight value for the addons, maybe something to recheck.

**Comment by raffaelj** [comment]
see #4
