### ISSUE TITLE
LineFormatter parser fails if message contains ()

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/cockpit-logger-addon#6]
example error:
"SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"

The level extraction is broken
![cockpit-logger-file-parse-error](https://user-images.githubusercontent.com/13042193/55764162-b454cb80-5a6a-11e9-8d3f-7e6ebe0bfe5a.png)

Both lines are error level. Using JSON instead works fine.

**Comment by pauloamgomes** [comment]
Can you provide the full line you have in the log file?

**Comment by raffaelj** [comment]
I actually skipped the idea of logging the event because of the way cockpit builds itself on each request like `check-backend-session` or `getLogContents`

I found the entry in the test log:
`[2019-04-08 23:55:27] cockpit.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) {"user":"raffael","request_uri":"/MyAppName/cockpit/call/logger/getLogContents","referrer":"http://localhost/MyAppName/recent-logs","http_method":"POST"} []`

I tested some possible cases with wrong database credentials while passing them to PDO and the log filled with hundreds of theses messages. But the logging test helped me to think about it.
